window.WORD_DATA = {
  textbook: {

    stage1: [
      { japanese: "awakeの過去形は？", english: "awoke" },
      { japanese: "bearの過去形は？", english: "bore" },
      { japanese: "beginの過去形は？", english: "begon" },
      { japanese: "biteの過去形は？", english: "bit" },
      { japanese: "blowの過去形は？", english: "blew" },
      { japanese: "breakの過去形は？", english: "broke" },
      { japanese: "chooseの過去形は？", english: "chose" },
      { japanese: "doの過去形は？", english: "did" },
      { japanese: "drawの過去形は？", english: "drew" },
      { japanese: "drinkの過去形は？", english: "drank" },
      { japanese: "driveの過去形は？", english: "drove" }
    ],
    stage2: [
      { japanese: "awakeの過去分詞形は？", english: "awoken" },
      { japanese: "bearの過去分詞形は？", english: "borne" },
      { japanese: "beginの過去分詞形は？", english: "begun" },
      { japanese: "biteの過去分詞形は？", english: "bitten" },
      { japanese: "blowの過去分詞形は？", english: "blown" },
      { japanese: "breakの過去分詞形は？", english: "broken" },
      { japanese: "chooseの過去分詞形は？", english: "chosen" },
      { japanese: "doの過去分詞形は？", english: "done" },
      { japanese: "drawの過去分詞形は？", english: "drawn" },
      { japanese: "drinkの過去分詞形は？", english: "drunk" },
      { japanese: "driveの過去分詞形は？", english: "driven" }
    ],
    stage3: [
      { japanese: "eatの過去形は？", english: "ate" },
      { japanese: "fallの過去形は？", english: "fell" },
      { japanese: "flyの過去形は？", english: "flew" },
      { japanese: "forbidの過去形は？", english: "forbade" },
      { japanese: "forgetの過去形は？", english: "forgot" },
      { japanese: "forgiveの過去形は？", english: "forgave" },
      { japanese: "freezeの過去形は？", english: "froze" },
      { japanese: "giveの過去形は？", english: "gave" },
      { japanese: "goの過去形は？", english: "went" },
      { japanese: "growの過去形は？", english: "grew" }
    ],
    stage4: [
      { japanese: "eatの過去分詞形は？", english: "eaten" },
      { japanese: "fallの過去分詞形は？", english: "fallen" },
      { japanese: "flyの過去分詞形は？", english: "flown" },
      { japanese: "forbidの過去分詞形は？", english: "forbidden" },
      { japanese: "forgetの過去分詞形は？", english: "forgotten" },
      { japanese: "forgiveの過去分詞形は？", english: "forgiven" },
      { japanese: "freezeの過去分詞形は？", english: "frozen" },
      { japanese: "giveの過去分詞形は？", english: "given" },
      { japanese: "goの過去分詞形は？", english: "gone" },
      { japanese: "growの過去分詞形は？", english: "grown" }
    ],
    stage5: [
   { japanese: "beatの過去分詞形は？", english: "beaten" },
      { japanese: "becomeの過去形は？", english: "became" },
      { japanese: "comeの過去形は？", english: "came" },
      { japanese: "runの過去形は？", english: "ran" }
    ],
    stage6: [
      { japanese: "賭ける", english: "bet" },
      { japanese: "破裂する", english: "burst" },
      { japanese: "投じる", english: "cast" },
      { japanese: "費用がかかる", english: "cost" },
      { japanese: "切る", english: "cut" },
      { japanese: "合う", english: "fit" },
      { japanese: "打つ", english: "hit" },
      { japanese: "傷つける", english: "hurt" },
      { japanese: "させる", english: "let" },
      { japanese: "置く", english: "put" },
      { japanese: "やめる", english: "quit" },
      { japanese: "読む", english: "read" },
      { japanese: "据え付ける", english: "set" },
      { japanese: "閉じる", english: "shut" },
      { japanese: "割る", english: "split" },
      { japanese: "広げる", english: "spread" },
    ],
    stage7: [
      { japanese: "bendの過去形、過去分詞形は？", english: "bent" },
      { japanese: "意見", english: "opinion" },
      { japanese: "理由", english: "reason" },
      { japanese: "結果", english: "result" },
      { japanese: "問題", english: "problem" },
      { japanese: "解決", english: "solution" },
      { japanese: "目標", english: "goal" },
      { japanese: "計画", english: "plan" },
      { japanese: "努力", english: "effort" },
      { japanese: "成功", english: "success" },
      { japanese: "失敗", english: "failure" },
      { japanese: "挑戦", english: "challenge" },
      { japanese: "成長", english: "growth" },
      { japanese: "変化", english: "change" },
      { japanese: "選択", english: "choice" }
    ],
    stage8: [
      { japanese: "社会", english: "society" },
      { japanese: "経済", english: "economy" },
      { japanese: "政治", english: "politics" },
      { japanese: "文化", english: "culture" },
      { japanese: "歴史", english: "history" },
      { japanese: "法律", english: "law" },
      { japanese: "教育", english: "education" },
      { japanese: "環境", english: "environment" },
      { japanese: "科学", english: "science" },
      { japanese: "技術", english: "technology" },
      { japanese: "研究", english: "research" },
      { japanese: "発展", english: "development" },
      { japanese: "影響", english: "influence" },
      { japanese: "責任", english: "responsibility" },
      { japanese: "役割", english: "role" }
    ],
    stage9: [
      { japanese: "理論", english: "theory" },
      { japanese: "仮説", english: "hypothesis" },
      { japanese: "分析", english: "analysis" },
      { japanese: "証拠", english: "evidence" },
      { japanese: "結論", english: "conclusion" },
      { japanese: "前提", english: "assumption" },
      { japanese: "視点", english: "perspective" },
      { japanese: "構造", english: "structure" },
      { japanese: "要因", english: "factor" },
      { japanese: "過程", english: "process" },
      { japanese: "傾向", english: "trend" },
      { japanese: "比較", english: "comparison" },
      { japanese: "評価", english: "evaluation" },
      { japanese: "判断", english: "judgment" },
      { japanese: "検証", english: "verification" }
    ],
    stage10: [
      { japanese: "主張", english: "claim" },
      { japanese: "批判", english: "criticism" },
      { japanese: "議論", english: "discussion" },
      { japanese: "論点", english: "issue" },
      { japanese: "根拠", english: "basis" },
      { japanese: "反論", english: "counter-argument" },
      { japanese: "合意", english: "agreement" },
      { japanese: "対立", english: "conflict" },
      { japanese: "提案", english: "proposal" },
      { japanese: "戦略", english: "strategy" },
      { japanese: "方針", english: "policy" },
      { japanese: "改革", english: "reform" },
      { japanese: "制度", english: "system" },
      { japanese: "管理", english: "management" },
      { japanese: "運営", english: "operation" }
    ],
    stage11: [
      { japanese: "倫理", english: "ethics" },
      { japanese: "価値", english: "value" },
      { japanese: "原則", english: "principle" },
      { japanese: "自由", english: "freedom" },
      { japanese: "平等", english: "equality" },
      { japanese: "権利", english: "right" },
      { japanese: "義務", english: "duty" },
      { japanese: "公正", english: "fairness" },
      { japanese: "正義", english: "justice" },
      { japanese: "尊重", english: "respect" },
      { japanese: "多様性", english: "diversity" },
      { japanese: "包摂", english: "inclusion" },
      { japanese: "差別", english: "discrimination" },
      { japanese: "責務", english: "obligation" },
      { japanese: "信頼", english: "trust" }
    ],
    stage12: [
      { japanese: "資源", english: "resource" },
      { japanese: "供給", english: "supply" },
      { japanese: "需要", english: "demand" },
      { japanese: "効率", english: "efficiency" },
      { japanese: "利益", english: "profit" },
      { japanese: "損失", english: "loss" },
      { japanese: "投資", english: "investment" },
      { japanese: "市場", english: "market" },
      { japanese: "競争", english: "competition" },
      { japanese: "価格", english: "price" },
      { japanese: "労働", english: "labor" },
      { japanese: "生産", english: "production" },
      { japanese: "消費", english: "consumption" },
      { japanese: "分配", english: "distribution" },
      { japanese: "影響力", english: "impact" }
    ],
    stage13: [
      { japanese: "観点", english: "viewpoint" },
      { japanese: "枠組み", english: "framework" },
      { japanese: "概念", english: "concept" },
      { japanese: "抽象的", english: "abstract" },
      { japanese: "具体的", english: "concrete" },
      { japanese: "複雑な", english: "complex" },
      { japanese: "単純な", english: "simple" },
      { japanese: "本質", english: "essence" },
      { japanese: "全体", english: "whole" },
      { japanese: "部分", english: "part" },
      { japanese: "関連", english: "relation" },
      { japanese: "相互作用", english: "interaction" },
      { japanese: "体系", english: "systematic" },
      { japanese: "機能", english: "function" },
      { japanese: "目的", english: "purpose" }
    ],
    stage14: [
      { japanese: "方法", english: "method" },
      { japanese: "手段", english: "means" },
      { japanese: "条件", english: "condition" },
      { japanese: "制約", english: "constraint" },
      { japanese: "仮定", english: "assumption" },
      { japanese: "選択肢", english: "option" },
      { japanese: "可能性", english: "possibility" },
      { japanese: "限界", english: "limit" },
      { japanese: "予測", english: "prediction" },
      { japanese: "基準", english: "criterion" },
      { japanese: "最適", english: "optimal" },
      { japanese: "代替", english: "alternative" },
      { japanese: "適応", english: "adaptation" },
      { japanese: "改善", english: "improvement" },
      { japanese: "応用", english: "application" }
    ],
    stage15: [
      { japanese: "専門", english: "specialty" },
      { japanese: "知識", english: "knowledge" },
      { japanese: "洞察", english: "insight" },
      { japanese: "創造性", english: "creativity" },
      { japanese: "継続", english: "persistence" },
      { japanese: "論理", english: "logic" },
      { japanese: "妥当性", english: "validity" },
      { japanese: "信頼性", english: "reliability" },
      { japanese: "客観性", english: "objectivity" },
      { japanese: "再現性", english: "reproducibility" },
      { japanese: "総合", english: "synthesis" },
      { japanese: "発見", english: "discovery" },
      { japanese: "革新", english: "innovation" },
      { japanese: "貢献", english: "contribution" }
    ]
  },

};